---
name: runner test

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  maui-build:
    runs-on: [self-hosted, macOS]
    steps:
      - uses: actions/checkout@v6

      - name: Prepare NuGet packages
        shell: bash
        run: |
          echo "The runners name is: $RUNNER_NAME"
